kind: Service
apiVersion: v1
metadata:
  name: muyash-backend
spec:
  ports:
  - name: http
    port: 3000
    targetPort: 3000
    protocol: TCP
  selector:
    app: muyash
    role: backend  
  type: LoadBalancer